# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev:  v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: check-added-large-files
        args: ['--maxkb=2000']
    -   id: check-ast
    -   id: detect-private-key
    -   id: detect-aws-credentials
        args: [ '--allow-missing-credentials' ]

- repo: local
  hooks:
      - id: isort
        name: formatting::isort
        entry: poetry run isort
        language: system
        types: [python]

- repo: local
  hooks:
      - id: black
        name: formatting::black
        entry: poetry run black
        language: system
        types: [python]

- repo: local
  hooks:
      - id: flake8
        name: linting::flake8
        entry: poetry run flake8
        language: system
        types: [python]

- repo: local
  hooks:
      - id: mypy
        name: typing::mypy
        language: system
        entry: poetry run mypy
        types: [python]
- repo: local
  hooks:
    - id: reuse-detect
      name: Common Library Reuse Detection
      entry: poetry run reuse-detect --staged
      language: system
      types: [python]
      stages: [commit]
      pass_filenames: false
